version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: qwerty1234
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: Belokurov
      MYSQL_PASSWORD: qwerty1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: node_app
    environment:
      DB_HOST: db
      DB_USER: Belokurov
      DB_PASSWORD: qwerty1234
      DB_NAME: mydatabase
      JWT_SECRET: "b6f2b8e0e5e7cbb1ec6e7b0c7f7e4d2c"
      JWT_EXPIRATION: "10m"
      JWT_REFRESH_EXPIRATION: "7d"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: